package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CArchives;
import com.cf.project.mybatis.model.CArchivesExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CArchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    long countByExample(CArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int deleteByExample(CArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int insert(CArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int insertSelective(CArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    List<CArchives> selectByExample(CArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    CArchives selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CArchives record, @Param("example") CArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CArchives record, @Param("example") CArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_archives
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CArchives record);
    
    /**
     * 删除照片
     * 
     */
    int delByRefid(String id);
    
    /**
     * 显示图片
     */
    List<Map<String, Object>> findImgPath(String id);

	List<Map<String, Object>> findImgVideoPath(String id);

	int delByRefidAndType(@Param(value = "id") String id, @Param(value = "type") String type);


	/*CArchives selectSharevByRefPrimaryKey(String id);

	CArchives selectSharepByRefPrimaryKey(String id);*/
}