package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CDataDate;
import com.cf.project.mybatis.model.CDataDateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CDataDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    long countByExample(CDataDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int deleteByExample(CDataDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int insert(CDataDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int insertSelective(CDataDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    List<CDataDate> selectByExample(CDataDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    CDataDate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CDataDate record, @Param("example") CDataDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CDataDate record, @Param("example") CDataDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CDataDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_data_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CDataDate record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);
}