package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CMeetingDelay;
import com.cf.project.mybatis.model.CMeetingDelayExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CMeetingDelayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    long countByExample(CMeetingDelayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int deleteByExample(CMeetingDelayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int insert(CMeetingDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int insertSelective(CMeetingDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    List<CMeetingDelay> selectByExample(CMeetingDelayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    CMeetingDelay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CMeetingDelay record, @Param("example") CMeetingDelayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CMeetingDelay record, @Param("example") CMeetingDelayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CMeetingDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_delay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CMeetingDelay record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);
}