package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CShjl;
import com.cf.project.mybatis.model.CShjlExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CShjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    long countByExample(CShjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int deleteByExample(CShjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int insert(CShjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int insertSelective(CShjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    List<CShjl> selectByExample(CShjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    CShjl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CShjl record, @Param("example") CShjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CShjl record, @Param("example") CShjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CShjl record); 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shjl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CShjl record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map); 
}