package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CTemporarycard;
import com.cf.project.mybatis.model.CTemporarycardExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CTemporarycardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    long countByExample(CTemporarycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int deleteByExample(CTemporarycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int insert(CTemporarycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int insertSelective(CTemporarycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    List<CTemporarycard> selectByExample(CTemporarycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    CTemporarycard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CTemporarycard record, @Param("example") CTemporarycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CTemporarycard record, @Param("example") CTemporarycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CTemporarycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CTemporarycard record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);

	int shkp(CTemporarycard pojo);

}