package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CPrint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_print.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_print.sbid
     *
     * @mbg.generated
     */
    private String sbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_print.dysj
     *
     * @mbg.generated
     */
    private String dysj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_print.dyys
     *
     * @mbg.generated
     */
    private String dyys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_print
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_print.id
     *
     * @return the value of c_print.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_print.id
     *
     * @param id the value for c_print.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_print.sbid
     *
     * @return the value of c_print.sbid
     *
     * @mbg.generated
     */
    public String getSbid() {
        return sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_print.sbid
     *
     * @param sbid the value for c_print.sbid
     *
     * @mbg.generated
     */
    public void setSbid(String sbid) {
        this.sbid = sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_print.dysj
     *
     * @return the value of c_print.dysj
     *
     * @mbg.generated
     */
    public String getDysj() {
        return dysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_print.dysj
     *
     * @param dysj the value for c_print.dysj
     *
     * @mbg.generated
     */
    public void setDysj(String dysj) {
        this.dysj = dysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_print.dyys
     *
     * @return the value of c_print.dyys
     *
     * @mbg.generated
     */
    public String getDyys() {
        return dyys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_print.dyys
     *
     * @param dyys the value for c_print.dyys
     *
     * @mbg.generated
     */
    public void setDyys(String dyys) {
        this.dyys = dyys;
    }

	public void setLastTime(Date dateTime) {
		// TODO Auto-generated method stub
		
	}

	public void setAddTime(Date dateTime) {
		// TODO Auto-generated method stub
		
	}
}