package com.cf.project.mybatis.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cf.project.mybatis.model.CMeetingUser;
import com.cf.project.mybatis.model.CMeetingUserExample;

public interface CMeetingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    long countByExample(CMeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int deleteByExample(CMeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int insert(CMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int insertSelective(CMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    List<CMeetingUser> selectByExample(CMeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    CMeetingUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CMeetingUser record, @Param("example") CMeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CMeetingUser record, @Param("example") CMeetingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_meeting_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CMeetingUser record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);
}