package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.SysInfo;
import com.cf.project.mybatis.model.SysInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    long countByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int deleteByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int insert(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int insertSelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    List<SysInfo> selectByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    SysInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysInfo record, @Param("example") SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysInfo record, @Param("example") SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysInfo record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);

	List<Map<String, Object>> findIp();
}