package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.CAttendanceTime;
import com.cf.project.mybatis.model.CAttendanceTimeExample;
import com.cf.util.JsonListResult;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CAttendanceTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    long countByExample(CAttendanceTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int deleteByExample(CAttendanceTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int insert(CAttendanceTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int insertSelective(CAttendanceTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    List<CAttendanceTime> selectByExample(CAttendanceTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    CAttendanceTime selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CAttendanceTime record, @Param("example") CAttendanceTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CAttendanceTime record, @Param("example") CAttendanceTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CAttendanceTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CAttendanceTime record);

	List<Map<String, Object>> findByHDPage(Map<String, Object> map);

	List<Map<String, Object>> findGsList(@Param("id") String id);

	List<Map<String, Object>> findsxbsjList(@Param("id") String id);
}