package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CAttendanceTime implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.fgs_id
     *
     * @mbg.generated
     */
    private String fgsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.time_start
     *
     * @mbg.generated
     */
    private String timeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.time_end
     *
     * @mbg.generated
     */
    private String timeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_attendance_time.last_time
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_attendance_time
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.id
     *
     * @return the value of c_attendance_time.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.id
     *
     * @param id the value for c_attendance_time.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.fgs_id
     *
     * @return the value of c_attendance_time.fgs_id
     *
     * @mbg.generated
     */
    public String getFgsId() {
        return fgsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.fgs_id
     *
     * @param fgsId the value for c_attendance_time.fgs_id
     *
     * @mbg.generated
     */
    public void setFgsId(String fgsId) {
        this.fgsId = fgsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.cname
     *
     * @return the value of c_attendance_time.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.cname
     *
     * @param cname the value for c_attendance_time.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.time_start
     *
     * @return the value of c_attendance_time.time_start
     *
     * @mbg.generated
     */
    public String getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.time_start
     *
     * @param timeStart the value for c_attendance_time.time_start
     *
     * @mbg.generated
     */
    public void setTimeStart(String timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.time_end
     *
     * @return the value of c_attendance_time.time_end
     *
     * @mbg.generated
     */
    public String getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.time_end
     *
     * @param timeEnd the value for c_attendance_time.time_end
     *
     * @mbg.generated
     */
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.remark
     *
     * @return the value of c_attendance_time.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.remark
     *
     * @param remark the value for c_attendance_time.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.state
     *
     * @return the value of c_attendance_time.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.state
     *
     * @param state the value for c_attendance_time.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.add_time
     *
     * @return the value of c_attendance_time.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.add_time
     *
     * @param addTime the value for c_attendance_time.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_attendance_time.last_time
     *
     * @return the value of c_attendance_time.last_time
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_attendance_time.last_time
     *
     * @param lastTime the value for c_attendance_time.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}