package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CJihua implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_jihua.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_jihua.jiemuId
     *
     * @mbg.generated
     */
    private String jiemuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_jihua.dates
     *
     * @mbg.generated
     */
    private String dates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_jihua.times
     *
     * @mbg.generated
     */
    private String times;
    private Date createtime;
    private String creater;
    private String deviceIds;
    
    private String publisher;
    private Date pubdate;
    private String checker;
    private Date checkdate;
    private String ispass;
    private Date subTime;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_jihua
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_jihua.id
     *
     * @return the value of c_jihua.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_jihua.id
     *
     * @param id the value for c_jihua.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_jihua.jiemuId
     *
     * @return the value of c_jihua.jiemuId
     *
     * @mbg.generated
     */
    public String getJiemuid() {
        return jiemuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_jihua.jiemuId
     *
     * @param jiemuid the value for c_jihua.jiemuId
     *
     * @mbg.generated
     */
    public void setJiemuid(String jiemuid) {
        this.jiemuid = jiemuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_jihua.dates
     *
     * @return the value of c_jihua.dates
     *
     * @mbg.generated
     */
    public String getDates() {
        return dates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_jihua.dates
     *
     * @param dates the value for c_jihua.dates
     *
     * @mbg.generated
     */
    public void setDates(String dates) {
        this.dates = dates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_jihua.times
     *
     * @return the value of c_jihua.times
     *
     * @mbg.generated
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_jihua.times
     *
     * @param times the value for c_jihua.times
     *
     * @mbg.generated
     */
    public void setTimes(String times) {
        this.times = times;
    }

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreater() {
		return creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public String getDeviceIds() {
		return deviceIds;
	}

	public void setDeviceIds(String deviceIds) {
		this.deviceIds = deviceIds;
	}

	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getPubdate() {
		return pubdate;
	}

	public void setPubdate(Date pubdate) {
		this.pubdate = pubdate;
	}

	public String getChecker() {
		return checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Date getCheckdate() {
		return checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	public String getIspass() {
		return ispass;
	}

	public void setIspass(String ispass) {
		this.ispass = ispass;
	}

	public Date getSubTime() {
		return subTime;
	}

	public void setSubTime(Date subTime) {
		this.subTime = subTime;
	}
	
	
	
	

	
	
    
}