package com.cf.project.mybatis.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cf.project.mybatis.model.CRoleFloor;
import com.cf.project.mybatis.model.CRoleFloorExample;

public interface CRoleFloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    long countByExample(CRoleFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int deleteByExample(CRoleFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int insert(CRoleFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int insertSelective(CRoleFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    List<CRoleFloor> selectByExample(CRoleFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    CRoleFloor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CRoleFloor record, @Param("example") CRoleFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CRoleFloor record, @Param("example") CRoleFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CRoleFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_floor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CRoleFloor record);
    
    /**
     * 获取角色关联的楼层信息
     * @param map
     * @return
     */
    List<Map<String,Object>> findFloorByRoleList(Map<String,Object> map);
}