package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.SysAuthority;
import com.cf.project.mybatis.model.SysAuthorityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    long countByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int deleteByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int insert(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int insertSelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    List<SysAuthority> selectByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    SysAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAuthority record);

    /**
     * 分页列表
     * @param map
     * @return
     */
    List<Map<String,Object>> findByHDPage(Map<String, Object> map);

    /**
     * 获取系统菜单树
     * @param map
     * @return
     */
    List<Map<String,Object>> findMenuTreeList(Map<String, Object> map);
    
    /**
     * 获取系统菜单树
     * @param map
     * @return
     */
    List<Map<String,Object>> findMenuTreeByRoleList(Map<String, Object> map);
    
    /**
     * 获取角色菜单树
     * @param map
     * @return
     */
    List<Map<String,Object>> findMenuTreeRoleList(Map<String, Object> map);
    /**
     * 获取改节点下是否有子节点
     * @param int
     * @return
     */
    int findByParentId(String id);
    
    List<String> findMenuByRole(Map<String, Object> map);
}