package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CTemporarycard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.zjhm
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.kh
     *
     * @mbg.generated
     */
    private String kh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.fwr
     *
     * @mbg.generated
     */
    private String fwr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.fwlc
     *
     * @mbg.generated
     */
    private String fwlc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.yxbz
     *
     * @mbg.generated
     */
    private String yxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_temporaryCard.last_time
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_temporaryCard
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.id
     *
     * @return the value of c_temporaryCard.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.id
     *
     * @param id the value for c_temporaryCard.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.name
     *
     * @return the value of c_temporaryCard.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.name
     *
     * @param name the value for c_temporaryCard.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.zjhm
     *
     * @return the value of c_temporaryCard.zjhm
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.zjhm
     *
     * @param zjhm the value for c_temporaryCard.zjhm
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.kh
     *
     * @return the value of c_temporaryCard.kh
     *
     * @mbg.generated
     */
    public String getKh() {
        return kh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.kh
     *
     * @param kh the value for c_temporaryCard.kh
     *
     * @mbg.generated
     */
    public void setKh(String kh) {
        this.kh = kh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.fwr
     *
     * @return the value of c_temporaryCard.fwr
     *
     * @mbg.generated
     */
    public String getFwr() {
        return fwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.fwr
     *
     * @param fwr the value for c_temporaryCard.fwr
     *
     * @mbg.generated
     */
    public void setFwr(String fwr) {
        this.fwr = fwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.fwlc
     *
     * @return the value of c_temporaryCard.fwlc
     *
     * @mbg.generated
     */
    public String getFwlc() {
        return fwlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.fwlc
     *
     * @param fwlc the value for c_temporaryCard.fwlc
     *
     * @mbg.generated
     */
    public void setFwlc(String fwlc) {
        this.fwlc = fwlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.yxbz
     *
     * @return the value of c_temporaryCard.yxbz
     *
     * @mbg.generated
     */
    public String getYxbz() {
        return yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.yxbz
     *
     * @param yxbz the value for c_temporaryCard.yxbz
     *
     * @mbg.generated
     */
    public void setYxbz(String yxbz) {
        this.yxbz = yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.add_time
     *
     * @return the value of c_temporaryCard.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.add_time
     *
     * @param addTime the value for c_temporaryCard.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_temporaryCard.last_time
     *
     * @return the value of c_temporaryCard.last_time
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_temporaryCard.last_time
     *
     * @param lastTime the value for c_temporaryCard.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}