package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CVisitor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.wchat_id
     *
     * @mbg.generated
     */
    private String wchatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.matter
     *
     * @mbg.generated
     */
    private String matter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.identity_card
     *
     * @mbg.generated
     */
    private String identityCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.vname
     *
     * @mbg.generated
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_visitor.last_time
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_visitor
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.id
     *
     * @return the value of c_visitor.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.id
     *
     * @param id the value for c_visitor.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.wchat_id
     *
     * @return the value of c_visitor.wchat_id
     *
     * @mbg.generated
     */
    public String getWchatId() {
        return wchatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.wchat_id
     *
     * @param wchatId the value for c_visitor.wchat_id
     *
     * @mbg.generated
     */
    public void setWchatId(String wchatId) {
        this.wchatId = wchatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.user_id
     *
     * @return the value of c_visitor.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.user_id
     *
     * @param userId the value for c_visitor.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.matter
     *
     * @return the value of c_visitor.matter
     *
     * @mbg.generated
     */
    public String getMatter() {
        return matter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.matter
     *
     * @param matter the value for c_visitor.matter
     *
     * @mbg.generated
     */
    public void setMatter(String matter) {
        this.matter = matter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.identity_card
     *
     * @return the value of c_visitor.identity_card
     *
     * @mbg.generated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.identity_card
     *
     * @param identityCard the value for c_visitor.identity_card
     *
     * @mbg.generated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.vname
     *
     * @return the value of c_visitor.vname
     *
     * @mbg.generated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.vname
     *
     * @param vname the value for c_visitor.vname
     *
     * @mbg.generated
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.state
     *
     * @return the value of c_visitor.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.state
     *
     * @param state the value for c_visitor.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.add_time
     *
     * @return the value of c_visitor.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.add_time
     *
     * @param addTime the value for c_visitor.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_visitor.last_time
     *
     * @return the value of c_visitor.last_time
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_visitor.last_time
     *
     * @param lastTime the value for c_visitor.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}