package com.cf.project.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class SysInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.val
     *
     * @mbg.generated
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.id
     *
     * @return the value of sys_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.id
     *
     * @param id the value for sys_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.name
     *
     * @return the value of sys_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.name
     *
     * @param name the value for sys_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.val
     *
     * @return the value of sys_info.val
     *
     * @mbg.generated
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.val
     *
     * @param val the value for sys_info.val
     *
     * @mbg.generated
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.bz
     *
     * @return the value of sys_info.bz
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.bz
     *
     * @param bz the value for sys_info.bz
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

	public void setLastTime(Date dateTime) {
		// TODO Auto-generated method stub
		
	}

	public void setAddTime(Date dateTime) {
		// TODO Auto-generated method stub
		
	}
}