package com.cf.project.mybatis.dao;

import com.cf.project.mybatis.model.SysRoleAuthority;
import com.cf.project.mybatis.model.SysRoleAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    long countByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int deleteByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int insert(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    List<SysRoleAuthority> selectByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    SysRoleAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleAuthority record);
    
    
    int deleteByRoleKey(String id);
    
    String findMenuCodeByRoleKey(String id);
}